vim.cmd("let g:netrw_liststyle = 3")

local opt = vim.opt

opt.cursorline = true -- Enable highlighting of the current line
opt.relativenumber = true -- Enable relative line numbers
opt.number = true -- Enable line numbers
opt.autowrite = true -- Enable automatic saving
opt.completeopt = "menu,menuone" -- Set autocomplete options
opt.conceallevel = 2 -- Hide *
opt.confirm = true -- Enable confirmation before exiting modified buffer
opt.expandtab = true -- Enable expanding tabs with space
opt.grepformat = "%f:%l:%c:%m" -- Set grep format
opt.ignorecase = true -- Enable case-insensitive searching
opt.inccommand = "nosplit" -- Show unsplitted preview
opt.jumpoptions = "view"
opt.laststatus = 3 -- global statusline
opt.linebreak = true -- Enable line breaking for long lines
opt.mouse = "a" -- Enable mouse mode
opt.pumheight = 10 -- Set popup menu height
opt.pumblend = 10 -- Set transparency level for popup menu
opt.scrolloff = 4 -- Set scroll offset
opt.shiftround = true -- Round shift operation
opt.shiftwidth = 2 -- Set shift width
opt.showmode = false -- Disable showing mode since we have statusline
opt.sidescrolloff = 8 -- Set side scroll offset
opt.signcolumn = "yes"
opt.smartcase = true -- Enable smart case
opt.smartindent = true -- Enable smart indent
opt.splitbelow = true -- Opens new split windows below the current window
opt.splitright = true -- Opens new split windows to the right of the current window
opt.tabstop = 2 -- Number of spaces that tabs should count for
opt.termguicolors = true -- Enable true colors in the terminal
opt.undofile = true -- Enable persistent undo with undo history stored in a file
opt.undolevels = 1000 -- Set maximum number of changes that can be undone to 10000
opt.updatetime = 200
opt.virtualedit = "block" -- Enable block-wise editing in virtual space
opt.winminwidth = 5 -- Minimum width of a window to 5 columns
opt.clipboard = vim.env.SSH_TTY and "" or "unnamedplus" -- Sync with system clipboard
-- opt.list = true -- Show invisible characters
vim.api.nvim_command("autocmd! BufWinEnter * if &filetype == 'man' | wincmd _ | endif")
